# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bar_archive_pb2 as bar__archive__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bar_archive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BarArchiveServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBeverageByID = channel.unary_unary(
                '/bar_archive.BarArchiveService/GetBeverageByID',
                request_serializer=bar__archive__pb2.GetBeverageByIDRequest.SerializeToString,
                response_deserializer=bar__archive__pb2.GetBeverageByIDResponse.FromString,
                _registered_method=True)
        self.AddBeverage = channel.unary_unary(
                '/bar_archive.BarArchiveService/AddBeverage',
                request_serializer=bar__archive__pb2.AddBeverageRequest.SerializeToString,
                response_deserializer=bar__archive__pb2.AddBeverageResponse.FromString,
                _registered_method=True)
        self.EditBeverage = channel.unary_unary(
                '/bar_archive.BarArchiveService/EditBeverage',
                request_serializer=bar__archive__pb2.EditBeverageRequest.SerializeToString,
                response_deserializer=bar__archive__pb2.EditBeverageResponse.FromString,
                _registered_method=True)
        self.RemoveBeverage = channel.unary_unary(
                '/bar_archive.BarArchiveService/RemoveBeverage',
                request_serializer=bar__archive__pb2.RemoveBeverageRequest.SerializeToString,
                response_deserializer=bar__archive__pb2.RemoveBeverageResponse.FromString,
                _registered_method=True)
        self.GetBeverages = channel.unary_unary(
                '/bar_archive.BarArchiveService/GetBeverages',
                request_serializer=bar__archive__pb2.GetBeveragesRequest.SerializeToString,
                response_deserializer=bar__archive__pb2.GetBeveragesResponse.FromString,
                _registered_method=True)


class BarArchiveServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBeverageByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBeverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditBeverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBeverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBeverages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarArchiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBeverageByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBeverageByID,
                    request_deserializer=bar__archive__pb2.GetBeverageByIDRequest.FromString,
                    response_serializer=bar__archive__pb2.GetBeverageByIDResponse.SerializeToString,
            ),
            'AddBeverage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBeverage,
                    request_deserializer=bar__archive__pb2.AddBeverageRequest.FromString,
                    response_serializer=bar__archive__pb2.AddBeverageResponse.SerializeToString,
            ),
            'EditBeverage': grpc.unary_unary_rpc_method_handler(
                    servicer.EditBeverage,
                    request_deserializer=bar__archive__pb2.EditBeverageRequest.FromString,
                    response_serializer=bar__archive__pb2.EditBeverageResponse.SerializeToString,
            ),
            'RemoveBeverage': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBeverage,
                    request_deserializer=bar__archive__pb2.RemoveBeverageRequest.FromString,
                    response_serializer=bar__archive__pb2.RemoveBeverageResponse.SerializeToString,
            ),
            'GetBeverages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBeverages,
                    request_deserializer=bar__archive__pb2.GetBeveragesRequest.FromString,
                    response_serializer=bar__archive__pb2.GetBeveragesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bar_archive.BarArchiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BarArchiveService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBeverageByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bar_archive.BarArchiveService/GetBeverageByID',
            bar__archive__pb2.GetBeverageByIDRequest.SerializeToString,
            bar__archive__pb2.GetBeverageByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBeverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bar_archive.BarArchiveService/AddBeverage',
            bar__archive__pb2.AddBeverageRequest.SerializeToString,
            bar__archive__pb2.AddBeverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditBeverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bar_archive.BarArchiveService/EditBeverage',
            bar__archive__pb2.EditBeverageRequest.SerializeToString,
            bar__archive__pb2.EditBeverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBeverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bar_archive.BarArchiveService/RemoveBeverage',
            bar__archive__pb2.RemoveBeverageRequest.SerializeToString,
            bar__archive__pb2.RemoveBeverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBeverages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bar_archive.BarArchiveService/GetBeverages',
            bar__archive__pb2.GetBeveragesRequest.SerializeToString,
            bar__archive__pb2.GetBeveragesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
